### ISSUE TITLE
How to apply tuning

### ISSUE THREAD

**Issue by ignaciocaamanio** [billhails/MuseScore-plugins#7]
I can't find where to select the tuning... Can the documentation instructions be more specific?

**Comment by billhails** [comment]
Hmm, when you run the plugin you should see this:
![Tuning Pop Up](https://raw.githubusercontent.com/billhails/MuseScore-plugins/develop/images/Tuning.png)
The apply button is quite visible. Maybe you have changed your default font and it's pushing the buttons out of the visible area?

**Comment by ignaciocaamanio** [comment]
Thanks !
